- name: message-1 
  ansible.builtin.degbug:
    msg: "hi from MSG-1"

- name: message-1 
  ansible.builtin.degbug:
    msg: "hi from MSG-2"

- name: message-1 
  ansible.builtin.degbug:
    msg: "hi from MSG-3"